[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]

[phases.cleanup]
cmds = [
  "rm -rf node_modules/.cache",
  "rm -rf node_modules/@types"
]

[start]
cmd = "npm start"